services:
  # ==========================================
  # 1. API SERVICE (Основной вход)
  # ==========================================
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scheduler-api
    command: ./scheduler
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./env/config.yaml:/etc/scheduler/config.yaml
    environment:
      - CONFIG_PATH=/etc/scheduler
    env_file:
      - .env
    networks:
      - scheduler-network

  # ==========================================
  # ИНФРАСТРУКТУРА
  # ==========================================
  db:
    image: postgres:17-alpine
    container_name: scheduler-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ucttp
    volumes:
      - scheduler-postgres:/var/lib/postgresql/data
    networks:
      - scheduler-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  scheduler-network:
    driver: bridge

volumes:
  scheduler-postgres: